### ISSUE TITLE
Equivalent config to the A1111 implementation?

### ISSUE THREAD

**Issue by wafflecomposite** [ssitu/ComfyUI_restart_sampling#10]
Not an issue with code, rather a question.

I had a good experience with using Restart in A1111, but it's simplified to a item in the sampler list there.

I would like help in understanding what sampler configuration in ComfyUI would at least be a *roughly* equivalent to the [A1111 implementation](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_samplers_extra.py), if possible. It's probably using `heun` whom what I can understand, but the rest of it is a mystery to me.

Thanks!

**Comment by blepping** [comment]
@wafflecomposite looks like it uses `heun` as the sampler and Karras for both schedulers.

if less than 20 steps, there are no restarts. this is like setting the restart segments to blank.

if it's between 20 and 36 steps inclusive it uses this segment: `[10,1,0.1,2.0]`

if it's over 36 steps it calculates `(steps // 4) + 1` (`//` is integer division) and uses that for the first value in the segment, `2` for the second value in the second and `0.1,2.0` like for the 20-36 segment. so for example if you set 50 steps it would use the segment `[13,2,0.1,2.0]` since `(50 // 4) + 1 = 13`. looks like it only ever adds one segment, only the nrestart, and k values in the segment change.

so it won't calculate it for you automatically but you should be able to determine what the segments would be relatively easily yourself and plug them into the segments field. i _think_ this is correct but i am not an expert and i only skimmed the code.

**Comment by ssitu** [comment]
Added by @blepping. You can now write `a1111` in the restart segments box for the behavior you requested. Check the [readme](https://github.com/ssitu/ComfyUI_restart_sampling?tab=readme-ov-file#segments) for more info.

**Comment by wafflecomposite** [comment]
Thanks!
